### ISSUE TITLE
Vulnerability From Other Admin Accounts

### ISSUE THREAD

**Issue by richardkentgates** [WordPress/two-factor#208]
If you view a user with two-step setup, you can uncheck the boxes, which doesn't actually leave them unchecked after saving, but it does remove the Primary mode, leaving it wide open without requiring two-step. So if someone gets in through an Admin with weak security, they can disable two-step for other users.

**Comment by kasparsd** [comment]
Thanks for reporting the issue @richardkentgates!

In #88 we're actually thinking of allowing admins to configuring 2FA for all users.

> So if someone gets in through an Admin with weak security, they can disable two-step for other users.

I haven't verified this but can't admins reset all user passwords in core WP?

**Comment by ericmann** [comment]
This is not necessarily a vulnerability but is usually the way access can be restored if an admin loses the means with which they provided a second step of authentication.

Use AWS for example (they support app-based 2FA by way of tools like Google Authenticator). If you and I are both admins on an account, and you drop your phone in a mud puddle, you've lost access to your account entirely. The only way to _restore_ access is to either call Amazon and work with a CSR to override your account and reset things, or ask me to disable 2FA for your account so you can log in and set up a new device.

I'm explicitly using the phrase "mud puddle" because this is the classic [mud puddle test](https://blog.cryptographyengineering.com/2012/04/05/icloud-who-holds-key/) when it comes to application security. It's a common discussion security engineers have when determining the trade-offs of any specific approach.

In other words, this is somewhat _by design_ and not a vulnerability of the system. Removing 2FA is an administrative-level operation open to anyone with administrative-level credentials.

**Comment by crstauf** [comment]
Suggestion: when 2FA settings are changed, send the user an email to confirm (or at least notify). Perhaps only send the email if changed by someone other than the account holder.

**Comment by iandunn** [comment]
I agree that admins should be able to manage 2FA of other admins. Forcing all users (or specific roles) to enable 2FA is covered by #255 / #239. Notifying folks when settings change is covered by #476 / #484.

So it seems safe to close this issue. Let me know if I missed a reason why it should stay open though.
