### ISSUE TITLE
Specify software licence used (if any)

### ISSUE THREAD

**Issue by axelsimon** [WordPress/two-factor#290]
Hi,
Unless i'm completely missing it, i can't find any mention of what licence this software is released under on this project.
The [wordpress plugin page](https://wordpress.org/plugins/two-factor/) states
> “Two-Factor” is open source software

but it seems to say that on every plugin page, so i'd like to see something more substantial on the product page, to clarify.

Thanks!

**Comment by kasparsd** [comment]
Thanks for bringing this up @axelsimon -- totally wasn't aware of it.

@georgestephanis What are your thoughts on this?

**Comment by axelsimon** [comment]
It might be obvious, but i still want to say: thanks for making two-factor and for making free and open source (or at least, that's the idea i'm getting!).

**Comment by BrookeDot** [comment]
There's a bit on licensing in [Plugin Handbook](https://developer.wordpress.org/plugins/plugin-basics/including-a-software-license/). Since it needs to be a GPL compatible plugin and the plugin may someday (hopefully) be merged into core I would think GPL v2 or later makes the most sense. 

The specific verbiage on the W.org plugin page comes as all WordPress plugins in the directory must be open source and GPL compatible. Here's a list of some other licenses we can use:
https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses

**Comment by swissspidy** [comment]
The `package.json` already clarifies GPL 2+ as the license, just saying:

https://github.com/georgestephanis/two-factor/blob/1354d5a5f77ee3d9ebad2266920f01920bde7cbe/package.json#L20

**Comment by axelsimon** [comment]
I would then suggest creating a LICENSE.md file in the repo, to make this explicit.
Here is a pull request to this end: https://github.com/WordPress/two-factor/pull/313
