### ISSUE TITLE
Yubico Key not working

### ISSUE THREAD

**Issue by 7php** [WordPress/two-factor#358]
hello, I am trying to register my security key (a USB-C Yubico key), it just reloads the page and the key is not registered.
I have tried on firefox and chrome, in vain.

Is there anything I am missing?

Platform details:
- I am using latest WordPress v5.4.1 and latest two-factor v0.6.0
- I am on HTTPS

**Comment by kasparsd** [comment]
Thanks for reporting the issue @7php!

The redirect usually indicates that the key was added successfully:

https://github.com/WordPress/two-factor/blob/529c973deb4677e45cc243b1336dd718aa472611/providers/js/fido-u2f-admin.js#L45

An error message should be displayed if it fails to add the key per this logic here:

https://github.com/WordPress/two-factor/blob/529c973deb4677e45cc243b1336dd718aa472611/providers/js/fido-u2f-admin.js#L31-L39

Could you please check the browser console for any errors or warnings when registering the key?

**Comment by 7php** [comment]
hi @kasparsd 

There is no error whatsoever on the console. But I have observe an interesting thing:

I need to wait like 15-20secs for the key to appear on table below `Security Keys`.

On the good side, feedback:
1) I have tried to login with the Key, it works fine with no hassle. Was instant trigger.
2) This plugin is awesome, keep up the good work. The only thing which would make it perfect would be integration with front-end pages like woocommerce login..etc

cheers

**Comment by kasparsd** [comment]
I'm glad you got it working @7php!

> I need to wait like 15-20secs for the key to appear on table below Security Keys.

This is probably unique to each browser and how it does the registration dance with the key.

> The only thing which would make it perfect would be integration with front-end pages like woocommerce login..etc

The login shortcode actually works as it redirects all requests to `wp-login.php` but the user settings shortcode is still missing due to how tightly coupled the current settings page is to user profile page:

https://github.com/WordPress/two-factor/blob/529c973deb4677e45cc243b1336dd718aa472611/class-two-factor-core.php#L65-L68

Issue #335 is tracking the progress of this task.

**Comment by 7php** [comment]
thank you dear @kasparsd
