### ISSUE TITLE
Compatibility With S2member Plugin

### ISSUE THREAD

**Issue by samueleastdev** [WordPress/two-factor#384]
Hi,

I wanted to enable Two Factor Authentication Plugin https://github.com/WordPress/two-factor on my website that is using s2Member.

If I disable the s2member plugin then the Two Factor Auth plugin works but when I enable it the plugin doesn’t work so I know the issue is between the two.

What I am asking would there be an option that would be causing the conflict the Two Factor plugin obviously uses a redirect at login to ask for an authentication code that s2member must be overriding somewhere?

Any suggestions where this might be to give me a head start?

Thanks

**Comment by kasparsd** [comment]
Thanks for reporting the issue @samueleastdev! There are often compatibility issues with other plugins that integrate with the login flow because of the way WordPress allows for these kinds of workflow modifications.

Unfortunately I'm personally not using the S2member plugin so I won't be able to debug this.

Could you please reopen this issue if you do figure out the exact place in code that would be causing this?
