### ISSUE TITLE
Use the locale of the user logging in for TOTP code

### ISSUE THREAD

**Issue by todeveni** [WordPress/two-factor#391]
User has two factor (TOTP) enabled and during log in user enters username and password and is presented with page for TOTP code. This page is currently translated using the locale of the site.

Since the user can select locale different than the actual site, could this be using the locale of the user?

**Comment by kasparsd** [comment]
The input form for the second-factor inherits the default WP login form which is why the input form uses the default locale.

The user is not considered authenticated until they complete the second faction and we clear their login state here:

https://github.com/WordPress/two-factor/blob/f10c28943ec4d71d78e510a6184e19d2d2f5c71a/class-two-factor-core.php#L434-L437

which is why WP doesn't load the user-configured locale.
