### ISSUE TITLE
The plugin does not have a valid header.

### ISSUE THREAD

**Issue by Trapulo** [WordPress/two-factor#433]
enabling the plugin, I have the error
"The plugin does not have a valid header."

**Comment by kasparsd** [comment]
Can you please confirm the steps to reproduce this? Which version of the plugin is causing it? How is it being activated?

The plugin header in the SVN repo is here and is valid:

https://plugins.trac.wordpress.org/browser/two-factor/trunk/two-factor.php#L11

This could be potentially caused by #422 though. I'll try to delete that other folder.

**Comment by Trapulo** [comment]
0.7.1, just installed from scratch. 
However I removed with a folder cleanup, then reinstalled it, and it's working

thanks
