### ISSUE TITLE
Uninstallation Not Deleting Plugin Data

### ISSUE THREAD

**Issue by PluginVulnerabilities** [WordPress/two-factor#630]
WordPress plugins [are supposed to clear out their data when uninstalled](https://developer.wordpress.org/plugins/plugin-basics/uninstall-methods/). As part of a security review of the plugin, we found that it doesn't currently do that.

It looks like there are 14 metadata keys that can be added to users' metadata that should be removed during uninstallation:

- _two_factor_nonce
- _two_factor_last_login_failure
- _two_factor_failed_login_attempts
- _two_factor_password_was_reset
- _two_factor_enabled_providers
- _two_factor_provider
- _two_factor_backup_codes
- _two_factor_email_token_timestamp
- _two_factor_email_token
- _two_factor_fido_u2f_register_request
- _two_factor_fido_u2f_login_request
- _two_factor_fido_u2f_registered_key
- _two_factor_totp_key
- _two_factor_totp_last_successful_login

There are [several methods that can be used to delete those](https://wordpress.stackexchange.com/questions/60769/best-practice-way-to-delete-user-meta-data-during-plugin-uninstall/112921).

This could be classified as a security issue because of what is stored. You [suggest reporting security issues](https://github.com/WordPress/two-factor/security) to a bounty program, but that only accepts reports on a limited range of vulnerabilities. [We raised that problem (and others)](https://github.com/WordPress/health-check/issues/465#issuecomment-2251047252) with WordPress' handling of reporting security issues through a bug bounty program with another plugin from WordPress in July, without a response or a change in your handling of the situation so far.

**Comment by jeffpaul** [comment]
My initial reaction here is to not remove these during plugin deactivation but perhaps during deletion/uninstallation we show an "are you sure" sort of message to alert the admin that this sort of data will be removed.  @kasparsd does that approach seem ok to you or some alternate handling?

**Comment by PluginVulnerabilities** [comment]
You are correct they shouldn't be deleted during deactivation, as the [relevant Plugin Handbook section mentions](https://developer.wordpress.org/plugins/plugin-basics/uninstall-methods/).

If an uninstallation method is set up, which would remove those, when clicking the Delete link for the plugin, it would show an alert that says:

> Are you sure you want to delete Two Factor and its data?

Right now it says:

> Are you sure you want to delete Two Factor?

**Comment by kasparsd** [comment]
Turns out we're not storing any options so we only need to take care of user meta. I've created a pull request for this #637.

The only consideration is that running the uninstall logic on a large multisite with many users could potentially time out. We could switch to a single query that deletes all user meta by keys to speed that up but I'll wait for a suggestion from @dd32 on this.

**Comment by dd32** [comment]
> We could switch to a single query that deletes all user meta by keys to speed that up but I'll wait for a suggestion from @dd32 on this.

That's not really an option, as you need to delete from object caches and any other system that sync's data based on hooks.

Instead of querying for all users and looping through meta_keys, what you could do is a direct `SELECT` query for matching rows and then delete by Meta ID's `delete_metadata_by_mid()`.

Personally, I don't see this as a security issue, so if not all data is removed, I don't see that as a critical problem.

**Comment by kasparsd** [comment]
@dd32 We're already using that method here:

https://github.com/WordPress/two-factor/blob/84051260d204080b1b1bff9bd81f03d728e881fd/providers/class-two-factor-fido-u2f.php#L354-L390

but that still requires a `delete_metadata_by_mid()` call for every single meta entry which is probably equally intensive in terms of object cache purges and processing time.

Let's merge it with the current approach and iterate if needed.

**Comment by kasparsd** [comment]
@dd32 Turns out [`deleta_metadata()`](https://developer.wordpress.org/reference/functions/delete_metadata/) has the final argument `$delete_all` which allows us to delete all user metas by key similar to how [`delete_post_meta_by_key()`](https://developer.wordpress.org/reference/functions/delete_post_meta_by_key/) does it for post meta (there isn't a matching function for users).

Any concerns with that approach?

**Comment by dd32** [comment]
Nope, that works for me too! I didn't realise it had the `$delete_all` parameter, and it properly clears the caches, so all is good by me.
